name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main

jobs:
  jekyll:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '3.1'
    - run: gem install bundler
    - run: bundle install
    - run: bundle exec jekyll build
    - uses: actions/upload-pages-artifact@v2
      with:
        path: _site

  deploy:
    needs: jekyll
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - uses: actions/deploy-pages@v2
